# py-profile build

version: 0.0.{build}
platform: x64

install:
  - ps: Install-Module psake
  - ps: Install-Module pester

build_script:
  - ps: Invoke-psake -taskList Clean, Package -properties @{"version"="$Env:APPVEYOR_BUILD_VERSION"} -ErrorAction Stop

test_script:
  - ps: Invoke-psake -taskList CiTest -properties @{"version"="$Env:APPVEYOR_BUILD_VERSION"} -ErrorAction Continue

artifacts:
  - path: ./dist/*.zip

# building tags triggers an infinite loop from github release tags
skip_tags: true

deploy:
  release: py-profile-$(APPVEYOR_BUILD_VERSION)
  description: 'personal dotfiles and ps scripts'
  provider: GitHub
  auth_token:
    secure: McXn11nJ4l06C283bftRirmxi8bEa2exPp3JfCaVfipZUZ5IUU6570Y6Y0CwKkEu
  on:
    branch: master
    appveyor_repo_tag: false
