# py-profile build

version: 0.0.{build}
platform: x64

install:
  - ps: Install-Module InvokeBuild
  - ps: Install-Module pester

build_script:
  - ps: Invoke-Build Clean, Assemble -version $Env:APPVEYOR_BUILD_VERSION -ErrorAction Stop

test_script:
  - ps: Invoke-Build CiTest -version $Env:APPVEYOR_BUILD_VERSION -ErrorAction Continue

artifacts:
  - path: ./dist/*.nupkg

# building tags triggers an infinite loop from github release tags
skip_tags: true

environment:
  bintray_api_key:
    secure: /EwVqeAku0ElP5+mpr8nYlRDPKgNAFMl35yV5RFmcObciYlgyIwzM2aJeLW4qbmj

before_deploy:
  - ps: nuget sources Add -Name bintray -Source https://api.bintray.com/nuget/pyranja/py-get -UserName pyranja -Password $Env:bintray_api_key

deploy:
  - provider: GitHub
    release: py-profile-$(APPVEYOR_BUILD_VERSION)
    description: 'personal dotfiles and ps scripts'
    auth_token:
      secure: McXn11nJ4l06C283bftRirmxi8bEa2exPp3JfCaVfipZUZ5IUU6570Y6Y0CwKkEu
    on:
      branch: master
      appveyor_repo_tag: false

  - provider: NuGet
    server: https://api.bintray.com/nuget/pyranja/py-get
    api_key:
      secure: j/VYazBzQe6lODyR+5Wp8T7unp1+UbJ5t3Jx09/Wr7Mb6DXnLcd+VWPR11XB0oApFUzIoMQIawka/xkB/a3Hug==
    skip_symbols: true
    on:
      branch: master
      appveyor_repo_tag: false
