# py-profile build

version: 0.0.{build}
platform: x64

install:
  - cinst pester

build_script:
  - ps: ./Package-Distributable.ps1 -ModuleVersion $Env:APPVEYOR_BUILD_VERSION -ErrorAction Stop

test_script:
  - ps: ./Test-Distributable.ps1

artifacts:
  - path: ./dist/*.zip

# building tags triggers an infinite loop from github release tags
skip_tags: true

deploy:
  release: py-profile-$(APPVEYOR_BUILD_VERSION)
  description: 'personal dotfiles and ps scripts'
  provider: GitHub
  auth_token:
    secure: CMJsFb4wYWDMhNBHSslK9SJPmRfc7vwu//9Uon7yMn/lmCnAI2PGg69/cFlQQy/L
  on:
    branch: master
    appveyor_repo_tag: false
